services:
  - type: web
    name: telegram-image-bot
    env: python
    buildCommand: pip install -r requirements.txt # <-- Yahan yeh command honi chahiye
    startCommand: gunicorn --workers 4 'run:app' --bind 0.0.0.0:$PORT
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK_URL
        sync: false
